#####################################################################
#
# fscheck.c is the name of your source code; you may change this.
# However, you must keep the name of the executable as "fscheck".
#
# Type "make" or "make fscheck" to compile your code
# 
# Type "make clean" to remove the executable (and any object files)
#
#####################################################################

CC=gcc
CFLAGS=-Wall -g -Werror

fscheck: fscheck.c
	$(CC) -o fscheck $(CFLAGS) fscheck.c

clean:
	$(RM) fscheck
